iyuuToken = '' # iyuu token。用于使用 Iyuu (https://github.com/ledccn/IYUUAutoReseed) 接口自动辅种
# 注释掉的配置项值为默认值
#iyuuDomain = '' # 配置 iyuu api 服务器的镜像或反向代理的域名或 URL。例如 'http://ufhy.top'。如果是域名，使用 https 协议
#reseedUsername = '' # Reseed username & password
#reseedPassword = '' # 用于使用 Reseed (https://github.com/tongyifan/Reseed-backend) 接口自动辅种
#siteInsecure = false # 禁用访问站点时的 TLS 证书校验
#siteTimeout = 5 # 访问网站超时时间(秒)
#siteImpersonate = "" # 设置访问站点时模仿的浏览器，ptool 会使用该浏览器的 TLS ja3 指纹、H2 指纹、http headers。默认模仿最新稳定版 Chrome on Windows x64 en-US
#siteProxy = '' # 使用代理访问 PT 站点（不适用于访问 BT 客户端）。格式为 'http://127.0.0.1:1080'。所有支持的代理协议: https://github.com/Noooste/azuretls-client?tab=readme-ov-file#proxy . 也支持通过 HTTP_PROXY & HTTPS_PROXY 环境变量设置代理
#brushEnableStats = false # 启用刷流统计功能
#publicTorrentRatioLimit = 0 # 公网的种子添加到BT客户端时，自动应用分享率(Up/Dl)限制，超过则停止做种。设为 0 无限制。仅对于 qBittorrent 有效
#hushshell = false # 如果设为 true, 启动 ptool shell 时将不显示欢迎信息
#shellMaxSuggestions = 5 # ptool shell 自动补全显示建议数量。设为 -1 禁用
#shellMaxHistory = 500 # ptool shell 命令历史记录保存数量。设为 -1 禁用


# 配置 BitTorrent 客户端
# 完整支持 qBittorrent  v4.1+ (推荐使用 qb v4.4+)
[[clients]]
name = 'local'
type = 'qbittorrent'
url = 'http://localhost:8085/'
username = 'admin'
password = 'adminadmin'
#localTorrentsPath = '' # 仅适用于本地的BT客户端。客户端的种子文件夹(QB 的 BT_backup 或 TR 的 torrents 文件夹)路径。对于 TR 必须配置本选项才能使用“导出种子”等命令；对于 QB 本配置可选(配置后会提高相关命令性能)
#qbittorrentNoLogin = false # 如果启用，不会发送登录请求。这将提高命令响应速度。需要在 QB Web UI 设置里开启跳过验证
#qbittorrentNoLogout = false # 如果启用，不会发送退出登录请求。这将提高命令响应速度，但会导致 QB web session 占用的内存不能及时释放
#brushMinDiskSpace = '5GiB' # 刷流：保留最小剩余磁盘空间
#brushSlowUploadSpeedTier = '100KiB' # 刷流：上传速度(/s)持续低于此值的种子将可能被删除
#brushMaxDownloadingTorrents = 6 # 刷流：位于下载状态的种子数上限
#brushMaxTorrents = 9999 # 刷流：种子数（所有状态）上限
#brushMinRatio = 0.2 # 刷流：最小 ratio (上传量/下载量)比例。ratio 持续低于此值的种子将可能被删除
#brushDefaultUploadSpeedLimit = '10MiB' # 刷流：默认最大上传速度限制(/s)

# 对 Transmission 客户端支持不完整且尚未充分测试。不建议用于刷流
# 支持 Transmission 2.80 ~ 3.00 (Transmission v4 还有问题)
[[clients]]
name = 'tr'
type = 'transmission'
url = 'http://localhost:9091/'
username = 'admin'
password = '123456'
#localTorrentsPath = '' # TR 需要配置 localTorrentsPath 才能使用"导出种子"等命令


# 配置 CookieCloud ( https://github.com/easychen/CookieCloud ) 后，可以从服务器同步站点 cookies 或导入站点
# 可以配置任意多个 CookieCloud 服务器信息
# 如果想要让某个 CookieCloud 服务器信息仅用于同步特定站点 cookies，加上 sites = ['sitename'] 这行配置
# 请参考 'cookiecloud' 命令帮助。同步站点 cookies 或导入站点会更新 ptool.toml 配置文件（已有的注释信息会丢失）
[[cookieclouds]]
#name = '' # 名称可选。设置后，cookiecloud 命令可以使用 --profile 参数只使用特定 CookieCloud 服务器信息同步
server = 'https://cookiecloud.example.com'
uuid = 'uuid'
password = 'password'


# 配置站点信息
[[sites]]
#name = '' # 手动指定站点名称。如果不指定，默认使用其 type 作为 name
type = 'keepfrds'
cookie = 'cookie_here'
#proxy = '' # 访问该站点使用的代理。优先级高于全局的 siteProxy 配置。格式为 'http://127.0.0.1:1080'
#torrentUploadSpeedLimit = '10MiB' # 站点单个种子上传速度限制(/s)
#brushTorrentMinSizeLimit = '0' # 刷流：种子最小体积限制。体积小于此值的种子不会被选择
#brushTorrentMaxSizeLimit = '1PiB' # 刷流：种子最大体积限制。体积大于此值的种子不会被选择
#brushMaxDiskSize = '' # 刷流：限制该站点刷流种子占用的磁盘空间上限。示例 '10TiB'。留空表示不限制
#brushAllowNoneFree = false # 是否允许使用非免费种子刷流
#brushAllowPaid = false # 是否允许使用'付费'种子刷流（付费种子：第一次下载或汇报时需要扣除积分）
#brushAllowHr = false # 是否允许使用HR种子刷流。程序不会特意保证HR种子的做种时长，所以仅当你的账户无视HR(如VIP)时开启此选项
#brushAllowZeroSeeders = false # 是否允许刷流任务添加当前0做种的种子到客户端
#brushExcludes = [] # 排除种子关键字列表。标题或副标题包含列表中任意项的种子不会被刷流任务选择
#brushAcceptAnyFree = false # 如果种子是免费的，则上传人数下载人数比和发布种子时间rtime的规则不限制
# 官方保种（officialseeding）示例配置（以 NexusPHP 为例，如 hhanclub 的 rescue.php）：
#officialSeedingSize = '5TiB' # 官方保种使用硬盘空间，与站点刷流/动态保种空间互不冲突
#officialSeedingTorrentMaxSize = '20GiB' # 官方保种单个种子大小上限
#officialSeedingTorrentsUrl = 'rescue.php' # 站点官方保种页面（未配置则默认使用该地址）
#officialSeedingMember = 5 # 列表中做种人数小于等于该值的视为候选，优先下载做种人数更少的；大于该值时无奖励（以添加时做种人数为准）
#timezone = 'Asia/Shanghai' # 网站页面显示时间的时区

# 新版 m-team (馒头) 不支持 Cookie。必须使用 token 鉴权。两种方法选择其一：
# 方法1(推荐)：使用 "x-api-key" header。"控制台 - 實驗室 - 存取令牌" 页面自行创建
# 方法2(模仿浏览器)：使用 "Authorization" header。浏览器登陆后 console 执行: localStorage.getItem("auth")
[[sites]]
type = 'mteam'
httpHeaders = [['x-api-key', 'xxxxx-xxxx-xxx']]
#httpHeaders = [['Authorization', 'xxxxxxxxxxxxxxxxxx']]


# 站点分组功能
# 定义分组后，大部分命令中 <site> 类型的参数可以使用分组名代替以指代多个站点，例如：
# 在 acg 分组的所有站点中搜索 'clannad' 关键词的种子: "ptool search acg clannad"
[[groups]]
name = 'acg'
sites = ['u2', 'kamept']


# 命令别名功能
# name (名称) & cmd (主命令行) 必需； minArgs (默认值为 0) & defaultArgs (默认值为空) 可选
# minArgs 是执行别名时必须传入的额外参数数量， defaultArgs 是额外参数可选部分的默认值
# 执行别名时，如果用户提供的额外参数数量 < minArgs ，程序会报错；如果用户提供的额外参数数量 == minArgs ，则 defaultArgs 会被追加到额外参数后面
# 例如，定义以下别名后：
# 运行 "ptool st" 等效于运行 "ptool status -t local"
# 运行 "ptool st tr" 等效于运行 "ptool status -t tr"
[[aliases]]
name = "st"
cmd = "status -t"
minArgs = 0
defaultArgs = "local"
