# 本 ptool.example.yaml 文件包含的配置项不完整。建议参考 ptool.example.toml 版本的示例配置文件。
iyuuToken: abcdefg
#brushEnableStats: false # 启用刷流统计功能
clients:
  -
    name: "local"
    type: "qbittorrent"
    url: "http://localhost:8085/" # qb web UI 地址
    username: "admin"
    password: "adminadmin"
    #brushMinDiskSpace: "5GB" # 刷流：保留最小空闲磁盘空间。
    #brushSlowUploadSpeedTier: "100KB" # 刷流：上传速度持续低于此值的种子将可能被删除
    #brushMaxDownloadingTorrents: 6 # 刷流：位于下载状态的种子数上限
    #brushMaxTorrents: 50 # 刷流：种子数（所有状态）上限
    #brushMinRatio: 0.2 # 刷流：最小上传/下载量比例
    #brushDefaultUploadSpeedLimit: "10MB" # 默认最大上传速度限制(/s)
sites:
  -
    name: "mt"
    type: "nexusphp"
    url: "https://kp.m-team.cc/"
    cookie: "cookie_here"
    #officialSeedingSize: "5TiB" # 官方保种使用硬盘空间
    #officialSeedingTorrentMaxSize: "20GiB" # 官方保种单个种子大小上限
    #officialSeedingTorrentsUrl: "rescue.php" # 官方保种页面（未配置则默认使用该地址）
    #officialSeedingMember: 5 # 候选阈值（≤该值）
    #officialSeedingOnlyFree: false # 是否仅下载“免费”种子
    #brushMaxDiskSize: "10TiB" # 刷流：限制该站点刷流种子占用的磁盘空间上限。不配置则不限制
    #torrentsUrl: "https://kp.m-team.cc/adult.php" # 单独设置种子列表页 url。如不指定，np 使用 torrents.php
    #timezone: "Asia/Shanghai" # 网站页面显示时间的时区
